language: objective-c
os: osx
osx_image: xcode7.3

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    matrix:
        - MATRIX_TARGET="-scheme FastEasyMapping -sdk iphonesimulator"

script:
    - set -o pipefail
    - xcodebuild clean test -workspace FastEasyMapping.xcworkspace $MATRIX_TARGET -enableCodeCoverage YES | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash)